version: "3.2"
services:
  server:
    image: cartesi/creepts-backend
    ports:
      - 8000:8000
  web:
    image: cartesi/creepts-web
    ports:
      - 8080:80
    environment:
      - "REACT_APP_API_URL=http://localhost:8000/api"
